server:
  port: 8086
spring:
  application:
    name: apigw
  zipkin:
    base-url: http://localhost:9411/
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customer/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
    fetch-registry: true
    register-with-eureka: true
