server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/frauddb
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
#  zipkin:
#    base-url: http://localhost:9411/
eureka:
  client:
    base-url: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true